twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        "%kernel.root_dir%/../vendor/knplabs/knp-paginator-bundle": KnpPaginator

    form_themes:
        - 'bootstrap_4_layout.html.twig'
