index:
    path: /
    controller: App\Controller\DefaultController::index

products:
    path: /products/
    controller: App\Controller\ProductsController:show

product:
    path: /products/product-{id}/
    controller: App\Controller\ProductController:showProduct

category:
    path: /products/category/{slug}/
    controller: App\Controller\CategoryController:showCategory

contact:
    path: /contact/
    controller: App\Controller\ContactController:show

cart:
    path: /cart/
    controller: App\Controller\CartController:showCart

checkout:
    path: /checkout/
    controller: App\Controller\CheckoutController:checkout

login:
    path: /login/
    controller: App\Controller\AuthController:login

logout:
    path: /logout/
    controller: App\Controller\AuthController:logout

admin_index:
    path: /admin/
    controller: App\Controller\AdminDefaultController:index

admin_users:
    path: /admin/users/
    controller: App\Controller\AdminUserController:show

admin_user_update:
    path: /admin/users/user-{id}/
    controller: App\Controller\AdminUserController:update

admin_user_create:
    path: /admin/users/create/
    controller: App\Controller\AdminUserController:create

admin_user_delete:
    path: /admin/users/delete/{id}/
    controller: App\Controller\AdminUserController:delete

admin_categories:
    path: admin/categories/
    controller: App\Controller\AdminCategoryController:show