index:
    path: /
    controller: App\Controller\DefaultController::index

products:
    path: /products/
    controller: App\Controller\ProductsController:show

product:
    path: /products/product-{id}/
    controller: App\Controller\ProductController:showProduct

category:
    path: /products/category/{slug}/
    controller: App\Controller\CategoryController:showCategory

cart:
    path: /cart/
    controller: App\Controller\CartController:showCart