index:
    path: /
    controller: App\Controller\DefaultController::index

products:
    path: /products/
    controller: App\Controller\ProductsController:show

product:
    path: /products/product-{id}/
    controller: App\Controller\ProductController:showProduct

category:
    path: /products/category/{slug}/
    controller: App\Controller\CategoryController:showCategory

contact:
    path: /contact/
    controller: App\Controller\ContactController:show

cart:
    path: /cart/
    controller: App\Controller\CartController:showCart

checkout:
    path: /checkout/
    controller: App\Controller\CheckoutController:checkout

login:
    path: /login/
    controller: App\Controller\AuthController:login

logout:
    path: /logout/
    controller: App\Controller\AuthController:logout

admin_index:
    path: /admin/
    controller: App\Controller\AdminDefaultController:index